service: panic-button

provider:
  name: aws
  runtime: rust
  region: ap-northeast-1
  memorySize: 128
  logRetentionInDays: 30

plugins:
  - serverless-rust
  - serverless-prune-plugin

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 2

functions:
  push:
    handler: push_handler
